import { createStore } from "vuex";

export default createStore({
  state: {
    articles: [
      {
        id: 0,
        imgsrc: require("@/assets/img/card-img1.png"),
        title: "Let’s Get Solution For Building Construction Work",
        category: "Kitchan Design",
        link: "#",
      },
      {
        id: 1,
        imgsrc: require("@/assets/img/card-img2.png"),
        title: "Low Cost Latest Invented Interior Designing <br> Ideas.",
        category: "Interior Design",
        link: "#",
      },
      {
        id: 2,
        imgsrc: require("@/assets/img/card-img3.png"),
        title: "Best For Any Office & Business Interior Solution",
        category: "Living Design",
        link: "#",
      },
      {
        id: 3,
        imgsrc: require("@/assets/img/card-img4.png"),
        title: "Let’s Get Solution For Building Construction Work",
        category: "Kitchan Design",
        link: "#",
      },
      {
        id: 4,
        imgsrc: require("@/assets/img/card-img5.png"),
        title: "Low Cost Latest Invented Interior Designing <br>Ideas.",
        category: "Interior Design",
        link: "#",
      },
      {
        id: 5,
        imgsrc: require("@/assets/img/card-img6.png"),
        title: "Best For Any Office & Business Interior Solution",
        category: "Living Design",
        link: "#",
      },
      {
        id: 6,
        imgsrc: require("@/assets/img/card-img6.png"),
        title: "Best For Any Office & Business Interior Solution",
        category: "Living Design",
        link: "#",
      },
      {
        id: 7,
        imgsrc: require("@/assets/img/card-img6.png"),
        title: "Best For Any Office & Business Interior Solution",
        category: "Living Design",
        link: "#",
      },
      {
        id: 8,
        imgsrc: require("@/assets/img/card-img6.png"),
        title: "Best For Any Office & Business Interior Solution",
        category: "Living Design",
        link: "#",
      },
      {
        id: 9,
        imgsrc: require("@/assets/img/card-img6.png"),
        title: "Best For Any Office & Business Interior Solution",
        category: "Living Design",
        link: "#",
      },
      {
        id: 10,
        imgsrc: require("@/assets/img/card-img6.png"),
        title: "Best For Any Office & Business Interior Solution",
        category: "Living Design",
        link: "#",
      },
      {
        id: 11,
        imgsrc: require("@/assets/img/card-img6.png"),
        title: "Best For Any Office & Business Interior Solution",
        category: "Living Design",
        link: "#",
      },
      {
        id: 12,
        imgsrc: require("@/assets/img/card-img5.png"),
        title: "Low Cost Latest Invented Interior Designing <br>Ideas.",
        category: "Interior Design",
        link: "#",
      },
      {
        id: 13,
        imgsrc: require("@/assets/img/card-img5.png"),
        title: "Low Cost Latest Invented Interior Designing <br>Ideas.",
        category: "Interior Design",
        link: "#",
      },
      {
        id: 14,
        imgsrc: require("@/assets/img/card-img5.png"),
        title: "Low Cost Latest Invented Interior Designing <br>Ideas.",
        category: "Interior Design",
        link: "#",
      },
      {
        id: 15,
        imgsrc: require("@/assets/img/card-img5.png"),
        title: "Low Cost Latest Invented Interior Designing <br>Ideas.",
        category: "Interior Design",
        link: "#",
      },
      {
        id: 16,
        imgsrc: require("@/assets/img/card-img5.png"),
        title: "Low Cost Latest Invented Interior Designing <br>Ideas.",
        category: "Interior Design",
        link: "#",
      },
      {
        id: 17,
        imgsrc: require("@/assets/img/card-img5.png"),
        title: "Low Cost Latest Invented Interior Designing <br>Ideas.",
        category: "Interior Design",
        link: "#",
      },
      {
        id: 18,
        imgsrc: require("@/assets/img/card-img1.png"),
        title: "Let’s Get Solution For Building Construction Work",
        category: "Kitchan Design",
        link: "#",
      },
      {
        id: 19,
        imgsrc: require("@/assets/img/card-img1.png"),
        title: "Let’s Get Solution For Building Construction Work",
        category: "Kitchan Design",
        link: "#",
      },
      {
        id: 20,
        imgsrc: require("@/assets/img/card-img1.png"),
        title: "Let’s Get Solution For Building Construction Work",
        category: "Kitchan Design",
        link: "#",
      },
      {
        id: 21,
        imgsrc: require("@/assets/img/card-img1.png"),
        title: "Let’s Get Solution For Building Construction Work",
        category: "Kitchan Design",
        link: "#",
      },
      {
        id: 22,
        imgsrc: require("@/assets/img/card-img1.png"),
        title: "Let’s Get Solution For Building Construction Work",
        category: "Kitchan Design",
        link: "#",
      },
      {
        id: 23,
        imgsrc: require("@/assets/img/card-img1.png"),
        title: "Let’s Get Solution For Building Construction Work",
        category: "Kitchan Design",
        link: "#",
      },
      {
        id: 24,
        imgsrc: require("@/assets/img/card-img2.png"),
        title: "Low Cost Latest Invented Interior Designing <br> Ideas.",
        category: "Interior Design",
        link: "#",
      },
      {
        id: 25,
        imgsrc: require("@/assets/img/card-img2.png"),
        title: "Low Cost Latest Invented Interior Designing <br> Ideas.",
        category: "Interior Design",
        link: "#",
      },
      {
        id: 26,
        imgsrc: require("@/assets/img/card-img2.png"),
        title: "Low Cost Latest Invented Interior Designing <br> Ideas.",
        category: "Interior Design",
        link: "#",
      },
      {
        id: 27,
        imgsrc: require("@/assets/img/card-img2.png"),
        title: "Low Cost Latest Invented Interior Designing <br> Ideas.",
        category: "Interior Design",
        link: "#",
      },
      {
        id: 28,
        imgsrc: require("@/assets/img/card-img2.png"),
        title: "Low Cost Latest Invented Interior Designing <br> Ideas.",
        category: "Interior Design",
        link: "#",
      },
      {
        id: 29,
        imgsrc: require("@/assets/img/card-img2.png"),
        title: "Low Cost Latest Invented Interior Designing <br> Ideas.",
        category: "Interior Design",
        link: "#",
      },
      {
        id: 30,
        imgsrc: require("@/assets/img/card-img2.png"),
        title: "Low Cost Latest Invented Interior Designing <br> Ideas.",
        category: "Interior Design",
        link: "#",
      },
    ],
    projectCards: [
      {
        id: 0,
        imgsrc: require("@/assets/img/card1.png"),
        link: "#",
        imgalt: "Modern Kitchan",
        title: "Modern Kitchan",
        info: "Decor / Artchitecture",
        class: "btrr main-figure",
      },
      {
        id: 1,
        imgsrc: require("@/assets/img/card2.png"),
        link: "#",
        imgalt: "Modern Kitchan",
        title: "Modern Kitchan",
        info: "Decor / Artchitecture",
        class: "btlr main-figure",
      },
      {
        id: 2,
        imgsrc: require("@/assets/img/card3.png"),
        link: "#",
        imgalt: "Modern Kitchan",
        title: "Modern Kitchan",
        info: "Decor / Artchitecture",
        class: "bbrr main-figure",
      },
      {
        id: 3,
        imgsrc: require("@/assets/img/card4.png"),
        link: "#",
        imgalt: "Modern Kitchan",
        title: "Modern Kitchan",
        info: "Decor / Artchitecture",
        class: "bblr main-figure",
      },
      {
        id: 31,
        imgsrc: require("@/assets/img/card1.png"),
        link: "#",
        imgalt: "Modern Kitchan",
        title: "Modern Kitchan",
        info: "Decor / Artchitecture",
        category: "Kitchan",
        class: "",
      },
      {
        id: 32,
        imgsrc: require("@/assets/img/card2.png"),
        link: "#",
        imgalt: "Modern Kitchan",
        title: "Modern Kitchan",
        info: "Decor / Artchitecture",
        category: "Kitchan",
        class: "",
      },
      {
        id: 33,
        imgsrc: require("@/assets/img/card3.png"),
        link: "#",
        imgalt: "Modern Kitchan",
        title: "Modern Kitchan",
        info: "Decor / Artchitecture",
        category: "Kitchan",
        class: "",
      },
      {
        id: 34,
        imgsrc: require("@/assets/img/card4.png"),
        link: "#",
        imgalt: "Modern Kitchan",
        title: "Modern Kitchan",
        info: "Decor / Artchitecture",
        category: "Kitchan",
        class: "",
      },
      {
        id: 4,
        imgsrc: require("@/assets/img/card-img5.png"),
        title: "Low Cost Latest Invented Interior Designing <br>Ideas.",
        category: "Living Area",
        info: "Decor / Artchitecture",
        link: "#",
      },
      {
        id: 5,
        imgsrc: require("@/assets/img/card-img6.png"),
        title: "Best For Any Office & Business Interior Solution",
        category: "Living Area",
        info: "Decor / Artchitecture",
        link: "#",
      },
      {
        id: 6,
        imgsrc: require("@/assets/img/card-img6.png"),
        title: "Best For Any Office & Business Interior Solution",
        category: "Living Area",
        info: "Decor / Artchitecture",
        link: "#",
      },
      {
        id: 7,
        imgsrc: require("@/assets/img/card-img6.png"),
        title: "Best For Any Office & Business Interior Solution",
        category: "Living Area",
        info: "Decor / Artchitecture",
        link: "#",
      },
      {
        id: 8,
        imgsrc: require("@/assets/img/card-img6.png"),
        title: "Best For Any Office & Business Interior Solution",
        category: "Living Area",
        info: "Decor / Artchitecture",
        link: "#",
      },
      {
        id: 9,
        imgsrc: require("@/assets/img/card-img6.png"),
        title: "Best For Any Office & Business Interior Solution",
        category: "Living Area",
        info: "Decor / Artchitecture",
        link: "#",
      },
      {
        id: 10,
        imgsrc: require("@/assets/img/card-img6.png"),
        title: "Best For Any Office & Business Interior Solution",
        category: "Living Area",
        info: "Decor / Artchitecture",
        link: "#",
      },
      {
        id: 11,
        imgsrc: require("@/assets/img/card-img5.png"),
        title: "Best For Any Office & Business Interior Solution",
        category: "Living Area",
        info: "Decor / Artchitecture",
        link: "#",
      },
      {
        id: 12,
        imgsrc: require("@/assets/img/card5.png"),
        title: "Low Cost Latest Invented Interior Designing <br>Ideas.",
        category: "Bathroom",
        info: "Decor / Artchitecture",
        link: "#",
      },
      {
        id: 13,
        imgsrc: require("@/assets/img/card6.png"),
        title: "Low Cost Latest Invented Interior Designing <br>Ideas.",
        category: "Bathroom",
        info: "Decor / Artchitecture",
        link: "#",
      },
      {
        id: 14,
        imgsrc: require("@/assets/img/card7.png"),
        title: "Low Cost Latest Invented Interior Designing <br>Ideas.",
        category: "Bathroom",
        info: "Decor / Artchitecture",
        link: "#",
      },
      {
        id: 15,
        imgsrc: require("@/assets/img/card8.png"),
        title: "Low Cost Latest Invented Interior Designing <br>Ideas.",
        category: "Bathroom",
        info: "Decor / Artchitecture",
        link: "#",
      },
      {
        id: 16,
        imgsrc: require("@/assets/img/card9.png"),
        title: "Low Cost Latest Invented Interior Designing <br>Ideas.",
        category: "Bathroom",
        info: "Decor / Artchitecture",
        link: "#",
      },
      {
        id: 17,
        imgsrc: require("@/assets/img/card10.png"),
        title: "Low Cost Latest Invented Interior Designing <br>Ideas.",
        category: "Bathroom",
        info: "Decor / Artchitecture",
        link: "#",
      },
      {
        id: 18,
        imgsrc: require("@/assets/img/card11.png"),
        title: "Let’s Get Solution For Building Construction Work",
        category: "Bed Room",
        info: "Decor / Artchitecture",
        link: "#",
      },
      {
        id: 19,
        imgsrc: require("@/assets/img/card12.png"),
        title: "Let’s Get Solution For Building Construction Work",
        category: "Bed Room",
        info: "Decor / Artchitecture",
        link: "#",
      },
      {
        id: 20,
        imgsrc: require("@/assets/img/card1.png"),
        title: "Let’s Get Solution For Building Construction Work",
        category: "Bed Room",
        info: "Decor / Artchitecture",
        link: "#",
      },
      {
        id: 21,
        imgsrc: require("@/assets/img/card2.png"),
        title: "Let’s Get Solution For Building Construction Work",
        category: "Bed Room",
        info: "Decor / Artchitecture",
        link: "#",
      },
      {
        id: 22,
        imgsrc: require("@/assets/img/card3.png"),
        title: "Let’s Get Solution For Building Construction Work",
        category: "Bed Room",
        info: "Decor / Artchitecture",
        link: "#",
      },
      {
        id: 23,
        imgsrc: require("@/assets/img/card6.png"),
        title: "Let’s Get Solution For Building Construction Work",
        category: "Bed Room",
        info: "Decor / Artchitecture",
        link: "#",
      },
      {
        id: 24,
        imgsrc: require("@/assets/img/card-img2.png"),
        title: "Low Cost Latest Invented Interior Designing <br> Ideas.",
        category: "Bed Room",
        info: "Decor / Artchitecture",
        link: "#",
      },
      {
        id: 25,
        imgsrc: require("@/assets/img/card8.png"),
        title: "Low Cost Latest Invented Interior Designing <br> Ideas.",
        category: "Bed Room",
        info: "Decor / Artchitecture",
        link: "#",
      },
      {
        id: 26,
        imgsrc: require("@/assets/img/card9.png"),
        title: "Low Cost Latest Invented Interior Designing <br> Ideas.",
        category: "Bed Room",
        info: "Decor / Artchitecture",
        link: "#",
      },
      {
        id: 27,
        imgsrc: require("@/assets/img/card10.png"),
        title: "Low Cost Latest Invented Interior Designing <br> Ideas.",
        category: "Bed Room",
        info: "Decor / Artchitecture",
        link: "#",
      },
      {
        id: 28,
        imgsrc: require("@/assets/img/card-img2.png"),
        title: "Low Cost Latest Invented Interior Designing <br> Ideas.",
        category: "Kitchan",
        info: "Decor / Artchitecture",
        link: "#",
      },
      {
        id: 29,
        imgsrc: require("@/assets/img/card-img2.png"),
        title: "Low Cost Latest Invented Interior Designing <br> Ideas.",
        category: "Kitchan",
        info: "Decor / Artchitecture",
        link: "#",
      },
      {
        id: 30,
        imgsrc: require("@/assets/img/card-img2.png"),
        title: "Low Cost Latest Invented Interior Designing <br> Ideas.",
        category: "Kitchan",
        info: "Decor / Artchitecture",
        link: "#",
      },
    ],
    detailArticles: [
      {
        category: "Kitchen",
        firstImgsrc: require("@/assets/img/article-photo1.png"),
        firstImgAlt: "firstImg",
        title1: "Let’s Get Solution for Building Construction Work",
        content1:
          "Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injecthumour, or randomised words which don't look even slightly believable.",
        content2:
          " Embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary.",
        blockquote: "The details are not the details. They make the design.",
        title2: "Design sprints are great",
        content3:
          "Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.",
        list: [
          "Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.",
          "Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.",
          "Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.",
        ],
        secondImgsrc: require("@/assets/img/article-photo1.png"),
        secondImgAlt: "secondImg",
        content4:
          "Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.",
      },
      {
        category: "Kitchen",
        firstImgsrc: require("@/assets/img/article-photo2.png"),
        firstImgAlt: "firstImg",
        title1: "Let’s Get Solution for Building Construction Work",
        content1:
          "Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injecthumour, or randomised words which don't look even slightly believable.",
        content2:
          " Embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary.",
        blockquote: "The details are not the details. They make the design.",
        title2: "Design sprints are great",
        content3:
          "Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.",
        list: [
          "Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.",
          "Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.",
          "Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.",
        ],
        secondImgsrc: require("@/assets/img/article-photo2.png"),
        secondImgAlt: "secondImg",
        content4:
          "Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.",
      },
      {
        category: "Bedroom",
        firstImgsrc: require("@/assets/img/card1.png"),
        firstImgAlt: "firstImg",
        title1: "Let’s Get Solution for Building Construction Work",
        content1:
          "Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injecthumour, or randomised words which don't look even slightly believable.",
        content2:
          " Embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary.",
        blockquote: "The details are not the details. They make the design.",
        title2: "Design sprints are great",
        content3:
          "Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.",
        list: [
          "Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.",
          "Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.",
          "Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.",
        ],
        secondImgsrc: require("@/assets/img/card1.png"),
        secondImgAlt: "secondImg",
        content4:
          "Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.",
      },
      {
        category: "Building",
        firstImgsrc: require("@/assets/img/card2.png"),
        firstImgAlt: "firstImg",
        title1: "Let’s Get Solution for Building Construction Work",
        content1:
          "Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injecthumour, or randomised words which don't look even slightly believable.",
        content2:
          " Embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary.",
        blockquote: "The details are not the details. They make the design.",
        title2: "Design sprints are great",
        content3:
          "Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.",
        list: [
          "Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.",
          "Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.",
          "Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.",
        ],
        secondImgsrc: require("@/assets/img/card2.png"),
        secondImgAlt: "secondImg",
        content4:
          "Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.",
      },
      {
        category: "Architecture",
        firstImgsrc: require("@/assets/img/card3.png"),
        firstImgAlt: "firstImg",
        title1: "Let’s Get Solution for Building Construction Work",
        content1:
          "Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injecthumour, or randomised words which don't look even slightly believable.",
        content2:
          " Embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary.",
        blockquote: "The details are not the details. They make the design.",
        title2: "Design sprints are great",
        content3:
          "Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.",
        list: [
          "Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.",
          "Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.",
          "Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.",
        ],
        secondImgsrc: require("@/assets/img/card3.png"),
        secondImgAlt: "secondImg",
        content4:
          "Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.",
      },
      {
        category: "Kitchen Planning",
        firstImgsrc: require("@/assets/img/card-img1.png"),
        firstImgAlt: "firstImg",
        title1: "Let’s Get Solution for Building Construction Work",
        content1:
          "Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injecthumour, or randomised words which don't look even slightly believable.",
        content2:
          " Embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary.",
        blockquote: "The details are not the details. They make the design.",
        title2: "Design sprints are great",
        content3:
          "Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.",
        list: [
          "Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.",
          "Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.",
          "Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.",
        ],
        secondImgsrc: require("@/assets/img/card-img1.png"),
        secondImgAlt: "secondImg",
        content4:
          "Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.",
      },
      {
        category: "Bedroom",
        firstImgsrc: require("@/assets/img/card-img2.png"),
        firstImgAlt: "firstImg",
        title1: "Let’s Get Solution for Building Construction Work",
        content1:
          "Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injecthumour, or randomised words which don't look even slightly believable.",
        content2:
          " Embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary.",
        blockquote: "The details are not the details. They make the design.",
        title2: "Design sprints are great",
        content3:
          "Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.",
        list: [
          "Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.",
          "Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.",
          "Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.",
        ],
        secondImgsrc: require("@/assets/img/card-img2.png"),
        secondImgAlt: "secondImg",
        content4:
          "Lorem ipsum dolor sit amet, adipiscing Aliquam eu sem vitae turpmaximus.posuere in.Contrary to popular belief.There are many variations of passages of Lorem Ipsum available, but the majority have suffered.",
      },
    ],
  },
  getters: {},
  mutations: {},
  actions: {},
  modules: {},
});
